### ISSUE TITLE
ImportError: cannot import name 'screenshot' from 'fastgrab' 

### ISSUE THREAD

**Issue by ghost** [mherkazandjian/fastgrab#9]
Traceback (most recent call last):
  File "fastgrab.py", line 2, in <module>
    from fastgrab import screenshot
  File "/root/Program/playground/opencv/fastgrab.py", line 2, in <module>
    from fastgrab import screenshot
ImportError: cannot import name 'screenshot' from 'fastgrab' (/root/Program/playground/opencv/fastgrab.py)

Does not work on debian 10 linux.
Please fix.

**Comment by mherkazandjian** [comment]
ok, tnx for reporting.

**Comment by mherkazandjian** [comment]
Your script is named `fastgrab.py`, so `from fastgrab import screenshot` resolves to your own file rather than the installed package. Rename your script (e.g. `app.py`) and the import will work. Closing as not a bug.
